---
# handlers file for deploy_app

- name: Start Nginx
  service: name=nginx state=started enabled=yes
- name: Start PHP-FPM
  service: name=php{{ php_ver }}-fpm state=started enabled=yes
- name: Reload Nginx
  command: nginx -s reload
- name: Reload PHP-FPM
  command: systemctl reload php{{ php_ver }}-fpm
